source 'http://rubygems.org'
gem 'vanity'
gem 'activerecord-jdbc-adapter'
gem 'default_value_for'
gem 'active_record_defaults'
gem 'enumerated_attribute'
# gem 'rails_indexes'
# gem 'ambitious_query_indexer'
gem 'searchlogic'
gem 'awesome_nested_set'
gem 'octopus'
gem 'acts_as_paranoid'
gem 'acts_as_list'
gem 'acts_as_audited'
gem 'attribute_normalizer'
gem 'paper_trail'
gem 'fog'
gem 'grape'
gem 'apiary'
gem 'twitter'
gem 'jammit-s3'
gem 'jammit'
gem 'resque_mailer'
gem 'eventmachine'
gem 'rev'
gem 'feedzirra'
gem 'resque'
gem 'backup'
# gem 'octopress'
gem 'capybara'
gem 'rack'
gem 'event_calendar'
gem 'mixlib-cli'
gem 'progressbar'
gem 'rcov'
gem 'configuration'
# gem 'refinery_cms'
gem 'travis'
gem 'guard'
gem 'couchrest'
# gem 'mongo_crm'
# gem 'blueprint-css'
gem 'sass'
gem 'fastercsv'
gem 'email_spec'
gem 'cucumber-nagios'
gem 'daemons'
gem 'daemon_controller'
gem 'daemon-spawn'
gem 'bundler'
gem 'capistrano'
gem 'deprecated';gem 'structured_warnings'
gem 'spork'
gem 'rdoc'
gem 'activemerchant'
gem 'mailcatcher'
gem 'mailman'
# gem 'action_mailer'
gem 'attr_encrypted'
gem 'hoptoad_notifier'
gem 'ews-api'
# gem 'fontue'
# gem 'altered_beast'
gem 'forem'
gem 'gosu'
gem 'open_gem'
gem 'hoe'
gem 'sinatra'
gem 'rack'
gem 'geokit'
gem 'grit';gem 'git'
# gem 'open_flash_chart'
gem 'nokogiri'
gem 'rest-client'
gem 'i18n'
gem 'rmagick'
gem 'pry';gem 'ripl'
gem 'dotfiles'
gem 'cinch'
# gem 'jquery'
gem 'execjs';gem 'therubyracer'
gem 'jasmine'
gem 'sprockets'
gem 'json'
gem 'devise_ldap_authenticatable'
gem 'rack'
gem 'log4r'
gem 'rack-maintenance'
gem 'turnout'
gem 'RedCloth'
gem 'mofo'
gem 'rspec-mocks'
gem 'fakeweb'
gem 'mongoid'
# gem 'archaeopteryx'
gem 'chronic'
# gem 'active_record'
# gem 'rubygems'
gem 'ocra'
gem 'will_paginate'
gem 'prawn'
gem 'showoff'
# gem 'redmine'
gem 'jrails'
gem 'rqrcode'
# gem 'timelinefu';
gem 'rails_admin'
# gem 'rails-templates'
gem 'devise'
gem 'cancan'
gem 'recaptcha'
gem 'railroady';gem 'rails-erd'
gem 'acts_as_commentable'
gem 'inherited_resources'
gem 'seed-fu'
gem 'paperclip'
gem 'factory_girl'
gem 'formtastic'
# gem 'rest_in_place'
gem 'newrelic_rpm'
gem 'simple-navigation'
gem 'friendly'
gem 'draper'
# gem 'ajaxful-rating'
gem 'thinking-sphinx'
gem 'subdomain-fu'
gem 'acts-as-taggable-on'
# gem 'actsaswizard'
gem 'faker'
gem 'ice_cube'
gem 'redis'
gem 'ruport'
gem 'active_support'
gem 'rvm'
gem 'whenever'
gem 'rake'
gem 'loofah'
gem 'god'
gem 'savon'
# gem 'diaspora'
gem 'rakismet'
gem 'mysql'
gem 'state_machine'
gem 'jekyll'
gem 'coderay'
gem 'chef'
gem 'datagrid'
gem 'haml'
gem 'term-ansicolor'
gem 'rspec'
gem 'redcar'
gem 'timecop'
gem 'rack-rewrite'
gem 'useragent'
# gem 'raphael'
gem 'ruby-processing'
# gem 'ruby_on_rails'
gem 'rack'
gem 'passenger'
# gem 'git-wiki'
gem 'happymapper'
